### ISSUE TITLE
Wildcard DNS record

### ISSUE THREAD

**Issue by george-oakling** [dnsimple/terraform-provider-dnsimple#25]
### Terraform Version
0.12.10

### Affected Resource(s)
- dnsimple_record

### Terraform Configuration Files
```hcl
resource "dnsimple_record" "redirect_0_wildcard" {
  domain = "*.xxx.com"
  name = ""
  type = "A"
  value = "1.1.1.1"
  ttl = 600
}
```

### Debug Output
Failed to create DNSimple Record: POST https://api.dnsimple.com/v2/XXXX/zones/*.domain.com/records: 404 Zone `*.domain.com` not foun

### Expected Behavior
The wildcard should be placed.

### Actual Behavior
404 - zone not found

### Steps to Reproduce
1. `terraform apply`

**Comment by boomshadow** [comment]
@george-oakling You get a 404 "not found" because the domain you enter directly correlates to an API URL in DNSimple's system. So by putting "*.xxx.com", the API call looks like this:  
`https://api.dnsimple.com/v2/REDACTED/zones/*.xxx.com/records`

You can see from your browser in DNSimple's web UI that your domain doesn't exist on that URL. It actually exists on:  
`https://dnsimple.com/a/REDACTED/domains/xxx.com/records`

Long story short, you need the following code:

```
resource "dnsimple_record" "redirect_0_wildcard" {
  domain = "xxx.com"
  name = "*"
  type = "A"
  value = "1.1.1.1"
  ttl = 600
}
```

That being said..... I actually can't get that to successfully work for me either. The API rejects it with `400 Validation failed`. Yet I can find proof of this method supposedly working for this guy: https://gitlab.oye.io/rauno/mantl/blob/855504c71c02210a42cb9fe1c9b95f32ec524f1a/terraform/dnsimple/dns/main.tf#L51-58

For now, I'm having to resort to making my wildcard entries manually 😢

**Comment by weppos** [comment]
> That being said..... I actually can't get that to successfully work for me either. The API rejects it with `400 Validation failed`. Yet I can find proof of this method supposedly working for this guy: https://gitlab.oye.io/rauno/mantl/blob/855504c71c02210a42cb9fe1c9b95f32ec524f1a/terraform/dnsimple/dns/main.tf#L51-58

This response should contain an error payload in the JSON with the individual validation errors. Any chance you can inspect the response and post it here? I'll be happy to take a look.

**Comment by boomshadow** [comment]
@weppos My apologies. I see my mistake. I was attempting to create a wildcard record that already existed. I needed to import first. I'm used to Route53 errors that tell me when I'm being dumb, creating records that already exist. I was confused by DNSimple's response. All good now!

**Comment by weppos** [comment]
> @weppos My apologies. I see my mistake. I was attempting to create a wildcard record that already existed. I needed to import first. I'm used to Route53 errors that tell me when I'm being dumb, creating records that already exist. I was confused by DNSimple's response. All good now!

Thanks for the feedback. FYI we actually return more detailed errors, but we currently don't expose them https://github.com/dnsimple/dnsimple-go/issues/60

**Comment by nestorsalceda** [comment]
Hey @george-oakling I would like to communicate that we just released a new version of the provider (0.14.0) that handles these issues.

Thank you for your patience!

**Comment by george-oakling** [comment]
Wow, thanks a lot! Much appreciated!

**Comment by weppos** [comment]
Closing as per latest updates.

**Comment by adiii717** [comment]
I am trying to create multiple AWS certificates, but when I tried to create zone records it ended up with

```
│ A matching record already exists for this zone, Another record already exists
│ for _12ee1d57338f45a0e6ef43cxxx.example.com, cannot add a CNAME, A
│ CNAME record exists for _12ee1d57338f45a0e6ef43xxx.example.com,
│ cannot add another record
```
Any to perform update in place?
